name: Rakit AmneziaWG Flint Komplit

on:
  workflow_dispatch:

jobs:
  build:
    name: Pembuatan Paket IPK AmneziaWG
    runs-on: ubuntu-22.04

    steps:
      - name: Ambil Kode Sumber
        uses: actions/checkout@v4

      - name: Siapkan Alat Sistem Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git gettext libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget

      - name: Tarik Repositori AmneziaWG
        run: |
          # Mengkloning langsung isi repositori ke folder utama
          git clone --depth=1 https://github.com/amnezia-vpn/amneziawg-openwrt.git .
          
      - name: Enkapsulasi Kompilasi Tools Mandiri
        run: |
          # Masuk langsung ke folder src karena tidak ada folder perantara
          cd src
          make CC=gcc
          mkdir -p ../bin/packages/ipq6000/
          cp amneziawg ../bin/packages/ipq6000/
          
      - name: Simpan Hasil Jadi (.IPK Paket)
        uses: actions/upload-artifact@v4
        with:
          name: Paket-AmneziaWG-Flint
          path: bin/packages/
